"""Group projector.

SPEC - declares encrypted, signer_type, dependencies, tables
project() - pure function: dict -> ProjectorResult
make_input(), make_event_data() - composable test builders

DEPS - declares dependencies needed for creation
create_pure() - pure function: deps -> CreateResult (no DB access)

Groups have polymorphic signing:
- Network-signed: signed_by == network_id (for all_users group)
- Peer-signed: signed_by == peer_shared_id (for user-created groups)

Groups create sub-events:
- group_key: symmetric key for encrypting group content

The pure create demonstrates chained creation:
1. Build group_key blob, compute key_id
2. Build group blob using key_id
3. Return both blobs for storage
"""

from typing import TypedDict, NotRequired
from projectors import ProjectorResult, CreateResult, BlobSpec, compute_event_id
import logging
import json
import crypto

log = logging.getLogger(__name__)


# ============================================================================
# TYPES - for autocomplete inside event dicts
# ============================================================================

class GroupEventData(TypedDict):
    type: str
    name: str
    signed_by: str  # network_id or peer_shared_id
    created_at: int
    key_id: str
    is_main: NotRequired[int]  # 1 if main group, 0 otherwise
    network_id: NotRequired[str]  # Network this group belongs to


class GroupInput(TypedDict):
    event_id: str
    event_data: GroupEventData
    recorded_by: str
    recorded_at: int
    key_id: str  # From encryption wrapper
    dependencies: dict  # Empty for groups (self-contained)


# ============================================================================
# SPEC - drives generic resolver
# ============================================================================

SPEC = {
    "encrypted": True,
    "signer_type": "admin",  # Polymorphic: network or peer_shared
    "dependencies": [],  # Groups are self-contained
    "tables": ["groups"],
}


# ============================================================================
# DEPS - dependencies needed for creation
# ============================================================================

DEPS = {
    # Private key for signing (peer's key OR explicit signer key)
    "private_key": {"type": "local_peer_key"},
    # Key material for group encryption (generated by resolver)
    "key_material": {"type": "generated_secret"},
}


# ============================================================================
# CREATE - pure function: deps -> CreateResult (chained creation)
# ============================================================================

class GroupCreateDeps(TypedDict):
    """Dependencies resolved for group creation."""
    peer_shared_id: str
    private_key: bytes
    key_material: bytes  # Generated 32-byte secret for group encryption
    # Optional overrides for network-signed groups
    signer_id: NotRequired[str]  # e.g., network_id
    signer_private_key: NotRequired[bytes]


def create_pure(
    deps: GroupCreateDeps,
    name: str,
    t_ms: int,
    is_main: bool = False,
    network_id: str | None = None,
) -> CreateResult:
    """Pure function to create a group event with its key.

    Demonstrates chained creation:
    1. Build group_key blob (local-only, plaintext)
    2. Compute key_id from blob hash
    3. Build group blob using key_id
    4. Return both blobs

    Args:
        deps: Resolved dependencies
        name: Group name
        t_ms: Timestamp
        is_main: Whether this is a main group
        network_id: Optional network ID for dependency ordering

    Returns:
        CreateResult with group_key blob and group blob
    """
    # 1. Build group_key blob (local-only, plaintext JSON)
    # This matches group_key.create() format exactly
    key_event_data = {
        'type': 'group_key',
        'key': crypto.b64encode(deps['key_material'])
    }
    key_blob = json.dumps(key_event_data, sort_keys=True).encode()
    key_id = compute_event_id(key_blob)

    # 2. Build key_data for wrapping the group event
    key_data = {
        'id': crypto.b64decode(key_id),
        'key': deps['key_material'],
        'type': 'symmetric'
    }

    # 3. Determine signer - either explicit (network) or default (peer_shared)
    signer_id = deps.get('signer_id') or deps['peer_shared_id']
    private_key = deps.get('signer_private_key') or deps['private_key']

    # 4. Build group event
    group_event_data = {
        'type': 'group',
        'name': name,
        'signed_by': signer_id,
        'created_at': t_ms,
        'key_id': key_id,
        'is_main': 1 if is_main else 0,
    }
    if network_id:
        group_event_data['network_id'] = network_id

    # Sign the group event
    signed_event = crypto.sign_event(group_event_data, private_key)

    # Wrap (canonicalize + encrypt)
    canonical = crypto.canonicalize_json(signed_event)
    group_blob = crypto.wrap(canonical, key_data, None)
    group_id = compute_event_id(group_blob)

    # Return both blobs in order (key first, then group)
    return CreateResult(
        blobs=[
            BlobSpec(blob=key_blob, event_id=key_id, event_type='group_key'),
            BlobSpec(blob=group_blob, event_id=group_id, event_type='group'),
        ],
        primary_id=group_id,
    )


# ============================================================================
# PROJECTOR - pure function: dict -> ProjectorResult
# ============================================================================

def project(input_dict: GroupInput) -> ProjectorResult:
    """Pure projection: dict -> result. No database access."""
    event_id = input_dict["event_id"]
    event_data: GroupEventData = input_dict["event_data"]
    recorded_by = input_dict["recorded_by"]
    recorded_at = input_dict["recorded_at"]

    # Validate event type
    if event_data.get("type") != "group":
        return ProjectorResult(valid=False, reason="Invalid event type")

    # Check required fields
    name = event_data.get("name")
    if not name:
        return ProjectorResult(valid=False, reason="Missing group name")

    signed_by = event_data.get("signed_by")
    if not signed_by:
        return ProjectorResult(valid=False, reason="Missing signed_by")

    key_id = event_data.get("key_id")
    if not key_id:
        return ProjectorResult(valid=False, reason="Missing key_id")

    # Signature is verified by resolver (polymorphic: network or peer_shared)
    # If we got here, signature was valid

    # Build output row
    group_row = {
        "group_id": event_id,
        "name": name,
        "signed_by": signed_by,
        "created_at": event_data["created_at"],
        "key_id": key_id,
        "is_main": event_data.get("is_main", 0),
        "network_id": event_data.get("network_id", ""),
        "recorded_by": recorded_by,
        "recorded_at": recorded_at,
    }

    return ProjectorResult(valid=True, tables={"groups": [group_row]})


# ============================================================================
# TEST BUILDERS - compose these to create test inputs (no DB required)
# ============================================================================

def make_event_data(
    name: str = "Test Group",
    signed_by: str = "peer_shared_123",
    created_at: int = 1000000,
    key_id: str = "key_123",
    is_main: int = 0,
    network_id: str = "",
) -> dict:
    """Build event_data for testing."""
    result = {
        "type": "group",
        "name": name,
        "signed_by": signed_by,
        "created_at": created_at,
        "key_id": key_id,
        "is_main": is_main,
    }
    if network_id:
        result["network_id"] = network_id
    return result


def make_input(
    event_id: str = "grp_123",
    event_data: dict | None = None,
    recorded_by: str = "peer_456",
    recorded_at: int = 1000001,
    key_id: str = "key_123",
) -> dict:
    """Build complete input dict for testing."""
    return {
        "event_id": event_id,
        "event_data": event_data or make_event_data(),
        "recorded_by": recorded_by,
        "recorded_at": recorded_at,
        "key_id": key_id,
        "dependencies": {},
    }


def make_network_signed_input(
    event_id: str = "grp_all_users",
    network_id: str = "net_123",
    name: str = "all_users",
    recorded_by: str = "peer_456",
) -> dict:
    """Build input for network-signed group (like all_users)."""
    return make_input(
        event_id=event_id,
        event_data=make_event_data(
            name=name,
            signed_by=network_id,  # Signed by network
            network_id=network_id,
            is_main=0,
        ),
        recorded_by=recorded_by,
    )
