-- Schema for remove_user event type
-- Tracks removed users to prevent their peers from syncing new messages
-- NOTE: User events remain in database for historical record (late joiners need to see user info)

-- NOTE: removed_users table is already created by remove.sql in the handlers directory
-- We just reference it here for documentation purposes.
-- If remove.sql doesn't exist or has been modified, ensure removed_users table exists:
--
-- CREATE TABLE IF NOT EXISTS removed_users (
--     user_id TEXT PRIMARY KEY,
--     removed_at INTEGER NOT NULL,
--     removed_by TEXT,
--     reason TEXT
-- );
--
-- CREATE INDEX IF NOT EXISTS idx_removed_users_time ON removed_users(removed_at);
